return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "awk",
      "bash",
      "c",
      "c_sharp",
      "cpp",
      "csv",
      "diff",
      "dockerfile",
      "go",
      "html",
      "http",
      "ini",
      "java",
      "javascript",
      "jinja",
      "jinja_inline",
      "jq",
      "json",
      "kotlin",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "nginx",
      "objc",
      "powershell",
      "printf",
      "python",
      "query",
      "regex",
      "smali",
      "ssh_config",
      "swift",
      "tmux",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
  }
}
