return {
  "nvzone/typr",
  dependencies = "nvzone/volt",
  opts = {
    mode = "phrases", -- words, phrases
    winlayout = "responsive",
    kblayout = "qwerty",
    wpm_goal = 100,
    numbers = false,
    symbols = false,
    random = false,
    phrases = {
      "An einem kühlen Herbstabend erfüllte das Rascheln der Blätter die Luft, während sich die Nachbarschaft auf den Krieg vorbereitete.",
      "Nach einem langen und anstrengenden Arbeitstag setzte sich Jane endlich in ihren Lieblingssessel und genoss eine heiße Tasse Tee am Kamin.",
      "Die Bibliothek war ein Zufluchtsort für Wissbegierige, mit meterhohen Regalen voller Bücher und dem feinen Duft alten Papiers.",
      "Unter dem weiten Sternenhimmel bauten die Wanderer ihre Zelte auf und erzählten Geschichten am Lagerfeuer.",
      "Die geschäftige Stadt vibrierte vor Energie – Autohupen, Stimmen und Vogelgezwitscher verschmolzen zu einer urbanen Symphonie.",
      "Auf den gewundenen Bergpfaden trug ein einsamer Wanderer seinen schweren Rucksack mit Entschlossenheit durch das unwegsame Gelände.",
      "Die Wellen krachten ans Ufer, während Kinder Sandburgen bauten und Familien die Sonne und die Meeresbrise genossen.",
      "Das kleine Dorf im Tal war umgeben von sanften Hügeln und Feldern in Grün und Gold, so weit das Auge reichte.",
      "Im tiefen Wald war die Luft erfüllt vom Zwitschern der Vögel und dem Rascheln der Blätter, während Eichhörnchen huschten.",
      "Der alte Bahnhof war ein Relikt vergangener Zeiten – mit abgewetzten Bänken und Wänden voller Erinnerungen.",
      "Die goldenen Sonnenstrahlen tauchten die Landschaft in warmes Licht, während der Morgentau im Gras funkelte.",
      "Die massive Eiche im Park spendete über Jahrzehnte Schatten und war fest verwurzelt in der Geschichte der Stadt.",
      "Die Bäckerei an der Ecke war berühmt für ihr frisches Brot und Gebäck, das Passanten mit seinem Duft verführte.",
      "Das klare blaue Wasser des Sees spiegelte die Berge ringsum und malte ein Bild wie aus einem Gemälde.",
      "Die Kopfsteinpflasterstraßen der Altstadt waren gesäumt von kleinen Läden und Cafes voller Leben.",
      "Der Garten war ein Farbenmeer aus blühenden Blumen, die Bienen und Schmetterlinge anlockten.",
      "Die alte Holzbrücke knarrte unter den Füßen des Wanderers, der vorsichtig den ruhigen Fluss überquerte.",
      "Das Sommerfest war voller Leben mit Fahrgeschäften, Spielen und Essensständen, die Besucher aus Nachbarorten anzogen.",
      "Der ruhige Strand bei Sonnenuntergang war ideal zum Nachdenken – mit sanften Wellen und einem Himmel in Orange und Rosa.",
      "Die Berghütte war ein gemütlicher Rückzugsort, umgeben von schneebedeckten Bäumen und Stille.",
      "Der geschäftige Markt war ein Fest für die Sinne – mit frischen Waren, Handwerk und exotischen Gewürzen.",
      "Die Zugfahrt durch das Land zeigte grüne Felder, grasende Kühe und idyllische Bauernhäuser.",
      "Das alte Herrenhaus am Straßenende zeugte mit seinen hohen Fenstern von vergangener Eleganz.",
      "Die sanften Hügel waren mit Wildblumen bedeckt, die sich im Wind wiegten und im Sonnenlicht leuchteten.",
      "Die enge Gasse lebte – Händler riefen und boten frisches Obst und handgemachten Schmuck an.",
      "Der Waldpfad war von hohen Bäumen gesäumt, deren Blätter das Sonnenlicht in Muster filterten.",
      "Von den Klippen bot sich ein atemberaubender Blick auf das weite Meer, während Möwen im Wind glitten.",
      "Der Dorfplatz war das Herz der Gemeinschaft, mit einem Brunnen und Bänken für Geschichten und Begegnungen.",
      "Die ruhige Bibliothek war ein Rückzugsort mit Bücherreihen und gemütlichen Leseplätzen.",
      "Der alte Leuchtturm trotzte den Wellen, sein Licht führte Schiffe sicher durch die Nacht.",
      "Das kleine Cafe an der Ecke war beliebt bei Einheimischen für Gespräche bei frischem Kaffee.",
      "Die Straßenkunst im Viertel brachte Farbe und Kreativität in die graue Umgebung.",
      "Der sanfte Bach schlängelte sich durch die Wiese, spiegelte Himmel und Wolken im klaren Wasser.",
      "Der Hafen war voller Leben – Fischer entluden ihren Fang, Händler feilschten um Preise.",
      "Der weitläufige Weinberg erstreckte sich bis zum Horizont und versprach eine reiche Ernte.",
      "Der stille See war ein Paradies für Tiere – Enten glitten dahin, Libellen tanzten im Licht.",
      "Die alten Ruinen erzählten von vergangener Größe mit bröckelnden Mauern und feinen Schnitzereien.",
      "Der Wanderweg schlängelte sich durch die Berge und bot atemberaubende Ausblicke ins Tal.",
      "Das kleine Fischerdorf war malerisch mit bunten Booten und Netzen in der Sonne.",
      "Die gemütliche Buchhandlung war ein Schatz voller seltener Werke und Geschichten zum Entdecken.",
      "Das Picknick am Fluss war ein Fest aus Essen, Lachen und der Schönheit der Natur.",
      "Die alte Burg auf dem Hügel erinnerte mit ihren Mauern an vergangene Zeiten und Geschichten.",
      "Die Gartenfeier war voller Lachen, Lichterketten und köstlicher Leckereien.",
      "Das ruhige Land war eine willkommene Pause vom Lärm der Stadt – mit Hügeln und weitem Himmel.",
      "Der Vergnügungspark war voller Lachen – Kinder rannten von Attraktion zu Attraktion.",
      "Der stille Bergsee war eine Oase, sein glattes Wasser spiegelte die umliegenden Gipfel.",
      "Der Regen prasselte gegen das Fenster, während drinnen eine Lampe warmes Licht auf das Buch warf.",
      "Ein alter Mann fütterte am Morgen die Tauben auf dem Marktplatz und nickte den Passanten freundlich zu.",
      "Im Café klirrten Tassen, während die Menschen ihre Gespräche mit Lächeln und Gesten untermalten.",
      "Die Kinder jagten Seifenblasen durch den Garten, bis der Himmel langsam dunkler wurde.",
      "Ein feiner Nebel zog durch die Gassen, verschluckte Geräusche und tauchte alles in Stille.",
      "Die Katze lag zusammengerollt auf dem Fensterbrett und blinzelte in die Nachmittagssonne.",
      "Die Wanduhr schlug Mitternacht, doch in der Küche roch es noch nach frischem Apfelkuchen.",
      "Im Zugabteil las eine junge Frau einen Liebesroman, während draußen Bäume vorbeiflogen.",
      "Der Wind spielte mit den Gardinen, als draußen die ersten Tropfen auf das Dach fielen.",
      "Das Zelt knisterte leise im Wind, während der Sternenhimmel über dem See funkelte.",
      "Im kleinen Atelier roch es nach Farbe und Lösungsmittel, während der Künstler seine Leinwand betrachtete.",
      "Ein Vogel sang sein Lied im Morgengrauen, lange bevor das Dorf erwachte.",
      "Die alte Schreibmaschine klackerte, als der Autor konzentriert an seinem nächsten Kapitel schrieb.",
      "Die Gitarre lehnte an der Wand, und durch das offene Fenster klang leise Musik vom Nachbarhaus.",
      "Am Kamin erzählte die Großmutter eine Geschichte aus ihrer Kindheit, und die Kinder lauschten gebannt.",
      "Der Duft von Lavendel lag in der Luft, während die Sonne langsam hinter den Hügeln verschwand.",
      "Die Straße war noch nass vom Regen, aber zwischen den Pflastersteinen glitzerte das Licht der Laternen.",
      "Der Schüler saß über seinem Heft und kritzelte Gedanken in die Ränder der Seiten.",
      "Der Turm der Kirche ragte über die Dächer, und seine Glocken läuteten zur vollen Stunde.",
      "Im Park saßen Liebespaare auf Bänken, teilten Eiscreme und Sonnenstrahlen.",
      "Der Klang eines fernen Klaviers erfüllte das Treppenhaus eines alten Mietshauses.",
      "Ein Ruderboot glitt lautlos über den See, während Nebelschwaden das Ufer verdeckten.",
      "Das Frühstück war gedeckt: frisches Brot, Marmelade, dampfender Kaffee und ein stiller Morgen.",
      "Die kleine Uhr auf dem Schreibtisch tickte leise, als draußen der Verkehr vorbeirauschte.",
      "Der erste Schnee fiel leise auf die Dächer, und Kinder jubelten auf dem Schulhof.",
      "Die Werkstatt roch nach Holz und Öl, und Späne bedeckten den Boden wie Konfetti.",
      "Der Balkon war mit Pflanzen überwuchert, ein grünes Paradies mitten in der Stadt.",
      "Ein alter Hund döste auf der Veranda und hob nur kurz den Kopf bei jedem Vorbeigehen.",
      "Das Theater war dunkel, der Vorhang fiel, und das Publikum klatschte begeistert.",
      "Im Gewächshaus blühten seltene Orchideen in allen Farben und Formen.",
      "Die Uhr im Bahnhof zeigte fünf nach acht, und der Zug fuhr mit einem Zischen ein.",
      "Der Lehrer schrieb mit Kreide an die Tafel, während es im Klassenzimmer raschelte.",
      "Ein Kind zog seinen Drachen über das Feld, der bunt flatternd in den Himmel stieg.",
      "Im Antiquariat roch es nach Leder, Papier und längst vergangenen Zeiten.",
      "Ein einzelnes Licht brannte auf dem Bootssteg, das Wasser spiegelte das Abendrot.",
      "Die Straßenbahn quietschte in der Kurve, während Passanten sich unter Regenschirmen duckten.",
      "Im Hinterhof summte eine Biene um die letzten Sommerblüten.",
      "Die Zeitung raschelte, als der alte Herr sie beim Frühstück entfaltete.",
      "Die Wanderer hielten an einem Berghang inne und blickten schweigend in die Ferne.",
      "Im Kino flackerte der Abspann über die Leinwand, während die Reihen sich langsam leerten.",
      "Auf dem Bauernhof krähten Hähne und die Sonne ging über den Feldern auf.",
      "Die Straßenlaterne war von Efeu umrankt und spendete schwaches Licht in der Nacht.",
      "Die Eisdiele hatte lange geöffnet, und der Sommerabend war voller Stimmen und Lachen.",
      "Ein Vogelbad auf dem Balkon war Treffpunkt für Spatzen, die darin planschten.",
      "Der Briefträger grüßte mit einem Lächeln und schob die Post in den Schlitz der alten Tür.",
      "Die Seilbahn zog langsam den Hang hinauf, während Touristen Fotos von der Aussicht machten.",
      "Der Waldweg war übersät mit Tannenzapfen, und es roch nach feuchter Erde.",
      "Der Klang einer Violine wehte aus dem offenen Fenster eines Musikzimmers.",
      "Im Kerzenschein las ein junges Paar gemeinsam ein Buch auf dem Sofa.",
      "Am Flussufer lagen Steine im Wasser, glattgeschliffen von der Zeit.",
    }, -- can be a table of strings
    insert_on_start = false,
  },
  cmd = { "Typr", "TyprStats" },
}
